#!/bin/sh
	case "$1" in
		start)
			echo "======================="
			echo "Invoking aesdchar_load" 
			echo "======================="
	 		/usr/bin/aesdchar_load
		 	# echo "Probing aesdchar driver module"
		 	# modprobe aesdchar
		 	# # /usr/bin/aesdchar_load
		 	# /usr/bin/aesdchar_unload
		 	# /usr/bin/aesdchar_load
		 	;;
		stop)
			echo "======================="
			echo "Invoking aesdchar_unload"
			echo "======================="
		  /usr/bin/aesdchar_unload
		  ;;
		*)
		 echo "Usage: $0 [start|stop]"
		 exit 1
	 esac

 # modprobe aesdchar
 # /usr/bin/aesdchar_load
 # /usr/bin/aesdchar_unload
 # /usr/bin/aesdchar_load
