#!/bin/sh
 case "$1" in
   start)
     echo "Loading custom Linux driver module(s)"
     # /etc/misc-modules/module_load faulty
     # /etc/misc-modules/module_load hello
     # /etc/scull/scull_load scull
     cd /etc/misc-modules
   	./module_load faulty
   	./module_load hello

   	echo "Loading custom scull module"
   	cd /etc/scull
     ./scull_load scull

    echo "========================================================="
    echo "ATTEMPTING TO LOAD AESDCHAR FROM LDDMODULES START SCRIPT"
    echo "========================================================="
    # insmod /lib/modules/$(uname -r)/extra/aesdchar.ko
    /usr/bin/aesdchar_load
    ;;
   stop)
     echo "Unloading custom Linux driver module(s)"
   	/etc/misc-modules/module_unload faulty
   	/etc/misc-modules/module_unload hello
   	/etc/scull/scull_unload scull
     ;;
   *)
     echo "Usage $0 {start|stop}"
     exit 1
 esac

 # modprobe faulty
 # modprobe hello
 # modprobe scull
